-- 사용자정보
DROP TABLE IF EXISTS User RESTRICT;

-- 가게리스트
DROP TABLE IF EXISTS Shop RESTRICT;

-- 예약정보
DROP TABLE IF EXISTS Reservation RESTRICT;

-- 메뉴
DROP TABLE IF EXISTS Menu RESTRICT;

-- 후기
DROP TABLE IF EXISTS Board RESTRICT;